# Arrays and Plotting

Many operations in the physical sciences involve vectors, which are generally used to succinctly summarize information about anything that has a magniutde and a direction. For example, the velocity of a car has a magnitude (speed) and direction, as does the acceleration. We will use the `array` data type from the `numpy` module to work with vectors. Because plotting helps visualize what vectors actually represent, we'll make figures using the `matplotlib` module.

## Reminder of Vectors

A visual representation of a vector $(x,y)$ is an arrow that goes from the origin $(0,0)$ to the given $(x,y)$ point. This is true for any number of dimensions. Given two such vectors, $(u_1, u_2)$ and $(v_1, v_2)$, we can add them according to the rule:
$$
(u_1, u_2) + (v_1, v_2) = (u_1 + u_2, v_1 + v_2)
$$
Subtraction is done in a similar way. You can also multiple vectors by a number. This number, called $a$ below, is usually denoted as a *scalar*:
$$
a \cdot (v_1, v_2) = (a v_1, a v_2)
$$
The inner product, also called a dot product, or scalar product, of the two vectors is a number:
$$
(u_1, u_2) \cdot (v_1, v_2) = u_1 v_1 + u_2 v_2.
$$
The length of a vector is defined by
$$
\lvert (v_1, v_2) \rvert = \sqrt{ (v_1, v_2) \cdot (v_1, v_2)} = \sqrt{v_1^2 + v_2^2}
$$
These same rules can be extrapolated to as many dimensions as necessary.

## Vectors in Python Programs

We will use the `array` object to represent vectors. They can be viewed as a variant of a list, but with the following assumptions and features:

- All elements must be of the same type, preferably `int`, `float`, or `complex`, for efficient numerical computing and storage.
- The number of elements must be known when the array is created.
- Arrays are not part of standard Python; instead we will use `numpy`.
- Arrays with one index are often called vectors.
- Arrays with two indices are used as an efficient data structure for tables, instead of lists of lists. They are also often referred to as matrices.

Two caveats to the above:
1) There is a an object type called `array` in Python, but this data type is not so efficient so we will ignore it.
2) The number of elements in an array *can* be changed, but at a substantial computing cost.

### Creating and Accessing Arrays in numpy

Let's start by taking a list and converting it to an array:

In [1]:
import numpy as np

vec = np.array([1,2])
print(vec)

[1 2]


It's also common to create an array initially filled with $n$ zero values:

In [2]:
n = 2
zero_vec = np.zeros(n)
print(zero_vec)

[0. 0.]


By default, the array is filled with elements of type `float`. A second argument can be used to specify a different data type:

In [ ]:
zero_vec = np.zeros(n, dtype=int)
print(zero_vec)

As we've already seen, it's convenient to produce an array with $n$ elements that are uniformly distributed in an interval $[a,b]$. The `numpy` function `linspace()` provides a convenient way to create such an array:

In [7]:
points = np.linspace(0,10,11)
print(points)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


You can access and slice arrays in the same way as lists. For example:

In [8]:
fewer_points = points[1:-1]
fewer_points[0] *= -1.0
print(fewer_points)

[-1.  2.  3.  4.  5.  6.  7.  8.  9.]


### Computing Coordinates and Function Values

With these basic operations, we can now build arrays of x values and y values. A simple example is:

In [6]:
import numpy as np

n = 11
xvalues = np.linspace(0, 10, n)
yvalues = np.zeros(n)

for i in range(n):
    yvalues[i] = xvalues[i]**2

print(yvalues)

[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


We could also have shortened the code using list comprehensions:

In [9]:
import numpy as np

n = 11
xvalues = np.linspace(0, 10, n)
yvalues = np.array([x**2 for x in xvalues])

print(yvalues)

[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


### Vectorization

Instead of looping over long lists, we can apply functions directly to arrays. For example:

In [10]:
def square(x):
    return x*x

xvalues = np.linspace(0, 10, 11)
yvalues = square(xvalues)

print(yvalues)

[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


This works because Python interprets the asterisk multiplication as:
$$
(u_1, u_2) * (v_1, v_2) = (u_1*v_1, u_2*v_2)
$$
This is similar to how we expect `+` and `-` to work for vectors. However, this does mean that `*` is **not** the same as a dot product.

In general, `numpy` provides its own versions of mathematical fucntions like `cos`, `sin`, `exp`, `log`, etc., which work with array arguments. This means that instead of writing the following:

In [11]:
import numpy as np

xvalues = np.linspace(0, 2*np.pi, 5)
yvalues = np.array([ np.sin(x) for x in xvalues ])
print(yvalues)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


You can instead replace this loop by a vector/array expression that is more readable:

In [12]:
import numpy as np

xvalues = np.linspace(0, 2*np.pi, 5)
yvalues = np.sin(xvalues) # use vectorization

print(yvalues)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


This is called *vectorization*.

Note: the `sin()` function from the `math` library does **not** accept array arguments, because of how it's implemented.

## Practice

Make an array of 20 $x$ values that are equally spaced between $[1,20]$.

In [14]:
vec = np.linspace(1,20,20)
print(vec)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


Now, define a function that calculates $f(x) = e^{-x}/x$. Make an array of values evaluated at each point in your list of $x$ values above using a list comprehension.

In [20]:
from numpy import e

def func(i):
    """Returns (e^-x)/x."""
    return e**(-i)/i

vec = np.linspace(1,20,20)

new_vec = np.array([func(i) for i in vec])
print(new_vec)

[3.67879441e-01 6.76676416e-02 1.65956895e-02 4.57890972e-03
 1.34758940e-03 4.13125363e-04 1.30268852e-04 4.19328285e-05
 1.37122005e-05 4.53999298e-06 1.51833644e-06 5.12017696e-07
 1.73871493e-07 5.93949085e-08 2.03934880e-08 7.03344842e-09
 2.43525748e-09 8.46109986e-10 2.94884023e-10 1.03057681e-10]


Finally, instead of using a list comprehension, make an array of values evaluated at each opint in your list of $x$ using vectorization.

In [ ]:
from numpy import e

def func(i):
    """Returns (e^-x)/x."""
    return e**(-i)/i

vec = np.linspace(1,20,20)

new_vec = func(vec)
print(new_vec)

[3.67879441e-01 6.76676416e-02 1.65956895e-02 4.57890972e-03
 1.34758940e-03 4.13125363e-04 1.30268852e-04 4.19328285e-05
 1.37122005e-05 4.53999298e-06 1.51833644e-06 5.12017696e-07
 1.73871493e-07 5.93949085e-08 2.03934880e-08 7.03344842e-09
 2.43525748e-09 8.46109986e-10 2.94884023e-10 1.03057681e-10]
