# Arrays and Plotting

## Advanced Arrays

Next we'll go over a few more useful operations with NumPy's arrays.

### Copying arrays

Similar to lists, using the assignment operator (`=`) refers to the original array:

In [1]:
import numpy as np

# Make array x, refer to it with a
x = np.array([0, 0, 0])
a = x

# Confirm that modifying x also modifies a
x[0] = 1
print(a)

[1 0 0]


To copy an array, you can use the `copy()` function:

In [2]:
x = np.array([0, 0, 0])
a = x.copy()

x[0] = 1
print(a)

[0 0 0]


### In-place Arithmetic

Let's consider two arrays of the same length, `a` and `b`. The expression `a += b` calculates the equivalent result as `a = a + b`. However, that's not the entire story.

In the statment `a = a + b`, the sum `a + b` is computed first, yielding a new array. The variable `a` is then set to reference this new array. The old array that `a` referenced is lost, unless another variable is assigned to it.

In the statement `a += b`, elements of `b` are added **directly** to elements of `a`. There is no intermediate array as in the previous method. This version is more efficient, since it avoids making an extra array.

To differentiate between the two methods, we say the operators `+=`, `*=`, and so on, perform *in-place* arithmetic on arrays.

Consider the following compund statement:

In [3]:
x = np.array([1.0, 2.0, 3.0])

# compound statement (readable)
a = (3*x**4 + 2*x + 4)/(x+1)
print(a)

[ 4.5        18.66666667 63.25      ]


The computation as shown above includes **seven** intermediate arrays:
```python
r1 = x**4
r2 = 3*r1
r3 = 2*x
r4 = r2 + r3
r5 = r4 + 4
r6 = x + 1
r7 = r5/r6
a = r7
```

With in-place arithmetic, we can instead only create **three** intermediate arrays:

In [4]:
x = np.array([1.0, 2.0, 3.0])

# in-place arithmetic (more efficient, less readable)
a = x.copy()   # new array (copy)
a **= 4
a *= 3
a += 2*x       # new array (2*x)
a += 4
a /= x + 1     # new array (x+1)
print(a)

[ 4.5        18.66666667 63.25      ]


It's common to perform many operations on very large arrays in computational science and engineering. By using in-place arithmetic you can save memory and array allocation time. However, the cost is less readable code.

**In summary**: if you're project is dominated by many calculations of large arrays, explore optimizing it using in-place arithmetic. If not, stick with simpler, more readable compound statments.

### Generalized Indexing

In addition to slicing arrays like we slice lists, you can also pass an list of indices. For example:

In [5]:
a = np.linspace(1,8,8) # simple list of integers from 1 to 8

# change the value of indices 1, 6, 7 to be 10
a[ [1,6,7] ] = 10
print(a)

[ 1. 10.  3.  4.  5.  6. 10. 10.]


In [6]:
# change elements 2 through 8, counting by 3s, to -2
a[ range(2,8,3) ] = -2
print(a)

[ 1. 10. -2.  4.  5. -2. 10. 10.]


We saw in the stepwise functions section that you can also use boolean arrays to generate an index set. The indices in the set will correspond to the indices for which the boolean array has `True` values. For example:

In [7]:
# Return slice of values that are less than 0
print(a[ a < 0 ])

[-2. -2.]


In the above, the condition `a < 0` returned the array `[False False  True False False True False False]`. When used to index an array, this turns into the list of indices that are true, i.e., `[2, 5]`.

You can also use this to change values the pass a certain criteria. For example, change the value of all elements that are less than 0:

In [8]:
# Change values less than 0 to be the maximum value in the list
a[ a < 0 ] = a.max()
print(a)

[ 1. 10. 10.  4.  5. 10. 10. 10.]


### Shape Manipulation

The *shape* of an array object describes the size of each dimension. This is different than the *size* of an array, which refers to the total number of elements.

Let's take a look at what this means for our array `a` from the previous examples:

In [9]:
# Reminder of what our array looks like
print('a =', a)

# The shape and size of the array
print('The shape of a:', a.shape)
print('The size of a:', a.size)
print('The length of a:', len(a))

a = [ 1. 10. 10.  4.  5. 10. 10. 10.]
The shape of a: (8,)
The size of a: 8
The length of a: 8


For a 1-dimensional array representing a vector, all the numbers are equal. Note that that `shape()` function always returns a `tuple`. Since a Python `tuple` is defined by a comma, even if there is only one element (the size of the 1-demensional array) it will always be followed by a comma.

We can use the `reshape()` function to change the dimensions of an existing array.

In [10]:
# Change a 1-demensional array with 8 elements into a 2-dimensional array with 4 elements in each dimension
b = a.reshape(2,4)
print('b =', b)
print('The shape of b:', b.shape)
print('The size of b:', b.size)
print('The length of b:', len(b))

b = [[ 1. 10. 10.  4.]
 [ 5. 10. 10. 10.]]
The shape of b: (2, 4)
The size of b: 8
The length of b: 2


Here, we see the shape of the array is now the tuple `(2,4)`, since there are two dimensions. While the size is the same, the length is now `2`. Since arrays are represented as nested lists, the length will return the size of the first dimension.

Note that the size of the new array must be the same as the size of the existing array.

In [11]:
# Try to change a 1x8 array into a 2x5 array
b = a.reshape(2,5)

ValueError: cannot reshape array of size 8 into shape (2,5)

This is our first example of how we'll represent matrices in Python, the subject of the next section.

## Practice

Consider the array of numbers in the cell below. Define two new arrays that are equal to:
$$
\frac{x^2 + 2}{x-2}
$$
For the first new array, use a compound statement. For the second new array, use in-place operators as much as possible.

In [16]:
x = np.array([1., 3., 5., 7., 9., 11.])
print((x**2+2)/(x-2))

a=x.copy()
a **= 2
a += 2
b = x.copy()
b -= 2
a /= b
print(a)

[-3.         11.          9.         10.2        11.85714286 13.66666667]
[-3.         11.          9.         10.2        11.85714286 13.66666667]


For the new array you've created, print the values that are less than 0 using boolean indexing.

Finally, print the shape of the array, change the shape to be $2x4$, and print the new shape of the array.