# Arrays and Plotting

## Higher-Dimiensional Arrays

### Matrices and Arrays

One dimensional arrays are useful for representing vectors, or lists of data. When mathematically modeling a system, you will also need two dimensional arrays for representing matrices, or tables of data.

A matrix of numbers is organized in columns and rows. For example:
$$
\left[
\begin{matrix}
0 & 12 & -1 & 5 \\
-1 & -1 & -1 & 0 \\
11 & 5 & 5 & -2
\end{matrix}
\right]
$$

The above is an example of a $3 \times 4$ matrix, i.e., a table with 3 rows and 4 columns.

If we associate the symbol $A$ with a matrix, $A_{i,j}$ denotes the number in row number $i$ and column number $j$. Counting rows and columns from 0, the above matrix has $A_{0,0} = 0$ and $A_{2,3}=-2$.

Matrices can be added and subtracted in the same piecwise way as vectors. They can can also be multiplied or divided by a scalar.

We can generalize the concept of vector or matrix to *array*, which holds quantities with $d$ indices, or has *rank* $d$. For $d=3$, an array $A$ has elements $A_{p,q,r}$. If $p$ goes from $0$ to $n_p-1$, $q$ from $0$ to $n_q-1$, and $r$ from $0$ to $n_r-1$, the array has $n_p \times n_q \times n_r$ total elements. The shape of this array is the tuple $(n_p, n_q, n_r)$.

### Creating Two-Dimensional Arrays

To make a two dimensional NumPy array, you can start by making a table out of nested lists:

In [1]:
# Two lists of temperatures in Celcius and Fahrenheit
Cdegrees = [ -30 + i*10 for i in range (3) ]
Fdegrees = [ 9/5*C + 32 for C in Cdegrees ]

# Nested lists make a table
table = [ [C, F] for C, F in zip(Cdegrees, Fdegrees) ]
print(table)

[[-30, -22.0], [-20, -4.0], [-10, 14.0]]


Similarly to lists and 1-dimensional arrays, you can now turn this table into a 2-dimensional array:

In [2]:
import numpy as np

# Make a matrix from nested lists
matrix = np.array(table)
print(matrix)

[[-30. -22.]
 [-20.  -4.]
 [-10.  14.]]


We can also use the `np.zeros` function, passing a shape instead of a simple length:

In [3]:
matrix0 = np.zeros((5,5))
print(matrix0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Accessing Two-Dimensional Arrays

You can access the elements of this matrix by in the same way you would access a list of lists, first specifying the outer list (row) and then the inner list (column):

In [4]:
# Access element in row 2, column 1
print(matrix[2][1])

14.0


For arrays, you will often see a different but equivalent synax:

In [5]:
# Access element in row 2, column 1
print(matrix[2,1])

14.0


Like we saw before, we can inspect the shape of this matrix using the `shape` attribute:

In [6]:
# Print shape information
print(matrix.shape)

(3, 2)


In the case of our temperature matrix, it has 3 rows and 2 columns.

We can use this to loop over all elements of the matrix using two `for` loops:

In [7]:
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        print(matrix[i,j])

-30.0
-22.0
-20.0
-4.0
-10.0
14.0


### Slicing Two-Dimensional Arrays

Arrays also allow for slicing each dimension in the same way you slice lists. If we wanted to extract the celcius degrees in column 1, we could write:

In [9]:
# Extract all rows of column 1
print(matrix[0:matrix.shape[0], 1])

# More compactly
print(matrix[:, 1])

[-22.  -4.  14.]
[-22.  -4.  14.]


Let's make a larger array to explore this further:

In [10]:
bigmatrix = np.linspace(1,30,30).reshape(5,6)
print(bigmatrix)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]]


If we wanted to make a slice of the rows 3 and above, for columns 2 to 4, we could write:

In [11]:
print(bigmatrix[3:, 2:5])

[[21. 22. 23.]
 [27. 28. 29.]]


Here, we started by specify `3:`, which picked out the rows starting with `19.` and `25.`. We then specified `2:5` which began with the column starting with `3.` and went to (but didn't include) the column starting with `5.`.

## Practice

Start by creating a $6 \times 6$ array filled with zeros.

In [23]:
matrix0 = np.zeros((6,6))
print(matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Now create a second $6 \times 6$ array where each entry is `10.0`.

In [24]:
matrix10 = matrix0 + 10
print(matrix10)

[[10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10.]]


For either array, change the corner values to be `-99.0`.

In [28]:
matrix0[0,0] = -99
matrix0[matrix.shape[0] - 1 ,0] = -99
matrix0[0,matrix.shape[1] - 1] = -99
matrix0[ matrix.shape[0] - 1, matrix.shape[1] - 1] = -99
print(matrix0)
 

[[-99.   0.   0.   0.   0. -99.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [-99.   0.   0.   0.   0. -99.]]


Print a slice of this array that only includes row indicies 1 through 4 and column indices 1 through 4.

In [31]:
print(matrix0[1:5, 1:5])
matrix0 = matrix0[1:5, 1:5]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Make a $4 \times 4$ identify matrix, i.e., a matrix with `1.0` in each cell where $i = j$ and zero otherwise.

In [32]:
for i in range(len(matrix0)):
    matrix0[i,i] = 1

print(matrix0)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
