# Arrays and Plotting

## Matrix Math

So far, we've only talked about the standard Python operators (`+`, `-`, `*`, `/`, and `**`) that are applied element-wise to NumPy arrays. To be useful for scientifc computing, arrays must also handle operations like matrix multiplication. The following section will introduce more advanced matrix operations using Python.

### Matrix Multiplication

To multiply two matrices together in Python, you can use the `@` operator. For example:

In [1]:
import numpy as np

matrixa = np.zeros((2,2)) + 1 # fill a 2x2 matrix with 1's
matrixb = np.zeros((2,2)) + 2 # fill a 2x2 matrix with 2's

print(matrixa @ matrixb)

[[4. 4.]
 [4. 4.]]


First, we defined a matrix filled with zeros and used the element-wise operator `+` to add `1` to each matrix element. We did the same for the next matrix, but instead added `2`. Finally, we performed the matrix multipication of the two using the `@` operator.

The `@` operator was introduced in Python 3.5. If you're looking at code that was written earlier than this, you will instead see the function `np.matmul()`. In general, the `@` operator provides a cleaner, more readable expression. For example, consider multiplying three objects together:

In [2]:
print(matrixa @ matrixa @ matrixa)
print(np.matmul(matrixa, np.matmul(matrixa, matrixa)))

[[4. 4.]
 [4. 4.]]
[[4. 4.]
 [4. 4.]]


### Multiplying a Matrix by a Vector

Similarly, you can multiply a matrix (2-D array) by a vector (1-D array).

In [3]:
veca = np.ones(2)

print(matrixa @ veca)

[2. 2.]


Because a 1-D array doesn't have any conception of being a row or column vector, the order doesn't matter:

In [4]:
print(veca @ matrixa)

[2. 2.]


Internally, when a 2-D array is multiplied by a 1-D array, the 1-D array is promoted to a 2-D array:
* If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions.
* If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions.

### Other Convenient Attributes and Functions

In the previous section you were asked to manually make the identity matrix. There is also a NumPy function for accomplishing this:

In [5]:
ident = np.eye(4)
print(ident)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


You can also calculate the *trace* of a matrix, i.e., the sum of its diagonal elements:

In [6]:
print(np.trace(ident))

4.0


Finally, ever NumPy array includes the `T` attribute, which contains the transpose of the array:

In [7]:
mat = np.linspace(1,25,25).reshape(5,5)
print(mat, '\n')
print(mat.T)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]] 

[[ 1.  6. 11. 16. 21.]
 [ 2.  7. 12. 17. 22.]
 [ 3.  8. 13. 18. 23.]
 [ 4.  9. 14. 19. 24.]
 [ 5. 10. 15. 20. 25.]]


### Linear Algebra Operations

For more advanced operations, NumPy offers the `linalg` module. This allows you to calculate the **inverse** of a square, non-singular matrix, the **determinant** of a square matrix, and the **eigen values** of a matrix, among other things.

Let's start by calculating the determinant of a matrix:

In [8]:
mat = np.array([[4, 7], 
                [2, 6]])
print(np.linalg.det(mat))

10.000000000000002


Next, we'll calculate the inverse and check that it works as expected:

In [9]:
mat = np.array([[4, 7], 
                [2, 6]])
inv = np.linalg.inv(mat)
print(inv, '\n')
print(mat @ inv)



[[ 0.6 -0.7]
 [-0.2  0.4]] 

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Finally, let's print the eigen values:

In [10]:
eigvals, eigvecs = np.linalg.eig(mat)
print(eigvals)
print(eigvecs)

[1.12701665 8.87298335]
[[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


## Practice

Imagine you are a biologist studying a species with two life stages: **Juveniles** and **Adults**.
1. **Survival:** Only 50% of Juveniles survive to become Adults. 80% of Adults survive each year.
2. **Reproduction:** Juveniles don't reproduce. Each Adult produces 2 new Juveniles per year.
We can represent the population at any time $t$ as a vector $\mathbf{v}_t$ and the transition rules as a matrix $M$.

To find the population for the next year, we use the formula:
$$
\mathbf{v}_{t+1} = M \mathbf{v}_t
$$
Where:
* $M = \begin{pmatrix} 0 & 2 \\ 0.5 & 0.8 \end{pmatrix}$
* $\mathbf{v}_t = \begin{pmatrix} \text{Juveniles} \\ \text{Adults} \end{pmatrix}$

Start by defining the matrices $M$ and $v_t$.

In [21]:
M = np.zeros((2,2))
M[0,0] = 0
M[0,1] = 2
M[1,0] = 0.5
M[1,1] = 0.8
print(M)

vt = np.zeros(2)
vt[0] = 1
vt[1] = 3
print(vt)

[[0.  2. ]
 [0.5 0.8]]
[1. 3.]


Next, perform the matrix multiplication: $M \mathbf{v}_t$.

In [ ]:
print(M @ vt)

[6.  2.9]


What is the juvenile population after 1 year? Can you calculate it after 10 years?

In [27]:
#number of years
n = 10

result = np.linalg.matrix_power(M, n) @ vt

print(f'After {n} years there would be {result[0]} juveniles and {result[1]} adults.')

After 10 years there would be 153.14609612800004 juveniles and 113.14667653120003 adults.
